#!/usr/bin/env -S mise -E dev exec -- bash
#MISE description="Run browser tests"
#MISE depends=["build"]

set -euo pipefail

mise run test:with-backend \
    ./mise-tasks/internal/lighthouse \
    ./mise-tasks/internal/test-e2e
