import { defineConfig } from "oxlint"

export default defineConfig({
    plugins: ["import"],
    categories: {
        correctness: "off",
    },
    env: {
        builtin: true,
        es2018: true,
    },
    ignorePatterns: [
        "dist/",
        "build/",
        ".turbo/",
        ".svelte-kit/",
        "node_modules/",
        "**/*.timestamp-*",
    ],
    rules: {
        complexity: ["error", { max: 10, variant: "modified" }],
        "constructor-super": "error",
        "for-direction": "error",
        "getter-return": "error",
        "no-async-promise-executor": "error",
        "no-case-declarations": "error",
        "no-class-assign": "error",
        "no-compare-neg-zero": "error",
        "no-cond-assign": "error",
        "no-const-assign": "error",
        "no-constant-binary-expression": "error",
        "no-constant-condition": "error",
        "no-control-regex": "error",
        "no-debugger": "error",
        "no-delete-var": "error",
        "no-dupe-class-members": "error",
        "no-dupe-else-if": "error",
        "no-dupe-keys": "error",
        "no-duplicate-case": "error",
        "no-empty": "error",
        "no-empty-character-class": "error",
        "no-empty-pattern": "error",
        "no-empty-static-block": "error",
        "no-ex-assign": "error",
        "no-extra-boolean-cast": "error",
        "no-fallthrough": "error",
        "no-func-assign": "error",
        "no-global-assign": "error",
        "no-import-assign": "error",
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "error",
        "no-loss-of-precision": "error",
        "no-misleading-character-class": "error",
        "no-new-native-nonconstructor": "error",
        "no-nonoctal-decimal-escape": "error",
        "no-obj-calls": "error",
        "no-prototype-builtins": "error",
        "no-redeclare": "error",
        "no-regex-spaces": "error",
        "no-self-assign": "error",
        "no-setter-return": "error",
        "no-shadow-restricted-names": "error",
        "no-sparse-arrays": "error",
        "no-this-before-super": "error",
        "no-unexpected-multiline": "error",
        "no-unreachable": "error",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "error",
        "no-unsafe-optional-chaining": "error",
        "no-unused-labels": "error",
        "no-unused-private-class-members": "error",
        "no-unused-vars": "error",
        "no-useless-backreference": "error",
        "no-useless-catch": "error",
        "no-useless-escape": "error",
        "no-with": "error",
        "require-yield": "error",
        "use-isnan": "error",
        "valid-typeof": "error",
        "import/namespace": "error",
        "import/default": "error",
        "import/no-named-as-default": "off",
        "import/no-named-as-default-member": "off",
        "import/no-duplicates": "warn",
    },
    overrides: [
        {
            files: ["**/*.{ts,tsx,mts,cts}"],
            rules: {
                "constructor-super": "off",
                "getter-return": "off",
                "no-class-assign": "off",
                "no-const-assign": "off",
                "no-dupe-class-members": "off",
                "no-dupe-keys": "off",
                "no-func-assign": "off",
                "no-import-assign": "off",
                "no-new-native-nonconstructor": "off",
                "no-obj-calls": "off",
                "no-redeclare": "off",
                "no-setter-return": "off",
                "no-this-before-super": "off",
                "no-unreachable": "off",
                "no-unsafe-negation": "off",
                "no-var": "error",
                "no-with": "off",
                "prefer-const": "error",
                "prefer-rest-params": "error",
                "prefer-spread": "error",
                "no-array-constructor": "error",
                "no-implied-eval": "off",
                "no-unused-expressions": "error",
                "no-useless-constructor": "error",
                "no-throw-literal": "off",
                "prefer-promise-reject-errors": "off",
                "require-await": "off",
                "typescript/ban-ts-comment": [
                    "error",
                    {
                        minimumDescriptionLength: 10,
                    },
                ],
                "typescript/no-duplicate-enum-values": "error",
                "typescript/no-dynamic-delete": "error",
                "typescript/no-empty-object-type": "error",
                "typescript/no-explicit-any": "error",
                "typescript/no-extra-non-null-assertion": "error",
                "typescript/no-extraneous-class": "error",
                "typescript/no-invalid-void-type": "error",
                "typescript/no-misused-new": "error",
                "typescript/no-namespace": "error",
                "typescript/no-non-null-asserted-nullish-coalescing": "error",
                "typescript/no-non-null-asserted-optional-chain": "error",
                "typescript/no-non-null-assertion": "error",
                "typescript/no-require-imports": "error",
                "typescript/no-this-alias": "error",
                "typescript/no-unnecessary-type-constraint": "error",
                "typescript/no-unsafe-declaration-merging": "error",
                "typescript/no-unsafe-function-type": "error",
                "typescript/no-wrapper-object-types": "error",
                "typescript/prefer-as-const": "error",
                "typescript/prefer-literal-enum-member": "error",
                "typescript/prefer-namespace-keyword": "error",
                "typescript/triple-slash-reference": "error",
                "typescript/unified-signatures": "error",
            },
            plugins: ["typescript"],
        },
        {
            files: ["**/*.{js,ts,tsx,jsx,mjs,cjs}"],
            rules: {
                "import/first": "error",
                "import/newline-after-import": "error",
                "import/no-duplicates": "error",
            },
            globals: {
                AsyncDisposableStack: "readonly",
                DisposableStack: "readonly",
                SuppressedError: "readonly",
            },
            env: {
                es2026: true,
                node: true,
            },
        },
        {
            files: ["**/*.{ts,tsx,mts,cts}"],
            rules: {
                "no-unused-vars": [
                    "error",
                    {
                        argsIgnorePattern: "^_",
                        varsIgnorePattern: "^_",
                        caughtErrorsIgnorePattern: "^_",
                    },
                ],
                "typescript/consistent-type-imports": "error",
            },
            plugins: ["typescript"],
        },
        {
            files: ["**/*.svelte"],
            rules: {
                "no-unused-vars": "off",
            },
        },
    ],
})
