name: Bug Report
title: "bug: "
description: File a bug report
labels: ["type:bug", "meta:needs-review"]
assignees:
  - pompydev

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this form!

  - type: checkboxes
    id: sanity-checks
    attributes:
      label: Sanity Checks
      description:
      options:
        - label: I have searched existing issues and didn't find any that were similar
          required: true

  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: What is happening? And if necessary, what was supposed to happen?
      value:
    validations:
      required: true
