name: Suggestion
title: "suggestion: "
description: feature requests and stuff
labels: ["type:suggestion", "meta:needs-review"]
assignees:
  - pompydev

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this form!

  - type: checkboxes
    id: sanity-checks
    attributes:
      label: Sanity Checks
      description:
      options:
        - label: I have searched existing issues and didn't find any that were similar
          required: true

  - type: textarea
    id: describe-your-suggestion
    attributes:
      label: Describe your suggestion
      value:
    validations:
      required: true
