export enum GameMode {
    DeathMatch,
    DemolitionDerby,
    ProtectLeader,
    ResourceCapture,
    Race,
    TankBattle,
    TankKing,
    CapturePoint,
    VehicleEscort,
    PackageDrop,
    ScudLaunch,
    BattleRoyale,
    Competitive,
    LobbyCompetitive,
    LobbyBR,
    Count,
}
