import { z } from "zod"

export enum Vehicle {
    TankLvl1 = "v00",
    TankLvl2 = "v01",
    TankLvl3 = "v02",
    APCLvl1 = "v10",
    APCLvl2 = "v11",
    APCLvl3 = "v12",
    Car = "v13",
    UNKNOWN_VEHICLE_14 = "v14",
    Jet1FinMachineGun = "v15",
    UNKNOWN_VEHICLE_16 = "v16",
    UNKNOWN_VEHICLE_17 = "v17",
    UNKNOWN_VEHICLE_18 = "v18",
    UNKNOWN_VEHICLE_19 = "v19",
    HeliLvl1 = "v20",
    HeliLvl2 = "v21",
    HeliLvl3 = "v22",
    HeliNoWeapon = "v23",
    Player = "v30",
    Jet1Fin = "v40",
    Jet2Fin = "v41",
    MachineGunTurret = "v50",
    UNKNOWN_VEHICLE_60 = "v60",
    UNKNOWN_VEHICLE_110 = "v110",
    UNKNOWN_VEHICLE_111 = "v111",
    UNKNOWN_VEHICLE_112 = "v112",
    UNKNOWN_VEHICLE_113 = "v113",
}

export const vehicleSchema = z.nativeEnum(Vehicle)

export const VehicleName: { [key in Vehicle]: string } = {
    [Vehicle.TankLvl1]: "Tank Lvl-1",
    [Vehicle.TankLvl2]: "Tank Lvl-2",
    [Vehicle.TankLvl3]: "Tank Lvl-3",
    [Vehicle.APCLvl1]: "APC Lvl-1",
    [Vehicle.APCLvl2]: "APC Lvl-2",
    [Vehicle.APCLvl3]: "APC Lvl-3",
    [Vehicle.Car]: "Car",
    [Vehicle.UNKNOWN_VEHICLE_14]: "Unknown Vehicle 14",
    [Vehicle.Jet1FinMachineGun]: "1 Fin Jet Machine Gun",
    [Vehicle.UNKNOWN_VEHICLE_16]: "Unknown Vehicle 16",
    [Vehicle.UNKNOWN_VEHICLE_17]: "Unknown Vehicle 17",
    [Vehicle.UNKNOWN_VEHICLE_18]: "Unknown Vehicle 18",
    [Vehicle.UNKNOWN_VEHICLE_19]: "Unknown Vehicle 19",
    [Vehicle.HeliLvl1]: "Heli Lvl-1",
    [Vehicle.HeliLvl2]: "Heli Lvl-2",
    [Vehicle.HeliLvl3]: "Heli Lvl-3",
    [Vehicle.HeliNoWeapon]: "Heli (No Weapon)",
    [Vehicle.Player]: "Person",
    [Vehicle.Jet1Fin]: "Jet (1 Fin)",
    [Vehicle.Jet2Fin]: "Jet (2 Fin)",
    [Vehicle.MachineGunTurret]: "Machine Gun Turret",
    [Vehicle.UNKNOWN_VEHICLE_60]: "Unknown Vehicle 60",
    [Vehicle.UNKNOWN_VEHICLE_110]: "Unknown Vehicle 110",
    [Vehicle.UNKNOWN_VEHICLE_111]: "Unknown Vehicle 111",
    [Vehicle.UNKNOWN_VEHICLE_112]: "Unknown Vehicle 112",
    [Vehicle.UNKNOWN_VEHICLE_113]: "Unknown Vehicle 113",
}
