import { z } from "zod"

export enum Weapon {
    AirStrike = "p09",
    BGM = "p11",
    TankLvl1 = "p52",
    APCLvl1 = "p53",
    HeliLvl1 = "p54",
    TankLvl2 = "p55",
    APCLvl2 = "p56",
    HeliLvl2 = "p57",
    TankLvl3 = "p58",
    APCLvl3 = "p59",
    HeliLvl3 = "p60",
    ARRifle = "p61",
    AKRifle = "p62",
    Pistol = "p63",
    HuntingRifle = "p64",
    RPG = "p65",
    Shotgun = "p66",
    SniperRifle = "p67",
    SMG = "p68",
    Homing = "p69",
    Grenade = "p71",
    HeliMinigun = "p74",
    TankMinigun = "p75",
    Knife = "p76",
    Revolver = "p78",
    Minigun = "p79",
    GrenadeLauncher = "p80",
    SmokeGrenade = "p81",
    Jet1Rockets = "p82",
    Jet1Homing = "p83",
    Jet1MachineGun = "p84",
    Jet2Rockets = "p85",
    Jet2Homing = "p86",
    Jet2MachineGun = "p87",
    Fists = "p88",
    VSS = "p89",
    FiftyCalSniper = "p90",
    MGTurret = "p91",
    Crossbow = "p92",
    SCAR = "p93",
    TacticalShotgun = "p94",
    VEK = "p95",
    Desert = "p96",
    Auto = "p97",
    LMG = "p98",
    UNRELEASED_WEAPON_99 = "p99",
    UnreleasedMace = "p100",
    RubberChicken = "p101",
    UnreleasedButterfly = "p102",
    Chainsaw = "p103",
    AKSMG = "p104",
    AutoSniper = "p105",
    UnreleasedAR = "p106",
    UnreleasedSawedOff = "p107",
    HealingPistol = "p108",
    UnreleasedMP7 = "p109",
    ImplosionGrenade = "p110",
    LaserTripMine = "p111",
    ConcussionGrenade = "p112",
    G3A3 = "p126",
}

export const weaponIDSchema = z.nativeEnum(Weapon)

export const WeaponName: { [key in Weapon]: string } = {
    [Weapon.AirStrike]: "Air Strike",
    [Weapon.BGM]: "BGM",
    [Weapon.UNKNOWN_WEAPON_52]: "Unknown Weapon 52",
    [Weapon.UNKNOWN_WEAPON_53]: "Unknown Weapon 53",
    [Weapon.UNKNOWN_WEAPON_54]: "Unknown Weapon 54",
    [Weapon.UNKNOWN_WEAPON_55]: "Unknown Weapon 55",
    [Weapon.UNKNOWN_WEAPON_56]: "Unknown Weapon 56",
    [Weapon.UNKNOWN_WEAPON_57]: "Unknown Weapon 57",
    [Weapon.UNKNOWN_WEAPON_58]: "Unknown Weapon 58",
    [Weapon.UNKNOWN_WEAPON_59]: "Unknown Weapon 59",
    [Weapon.UNKNOWN_WEAPON_60]: "Unknown Weapon 60",
    [Weapon.ARRifle]: "AR Rifle",
    [Weapon.AKRifle]: "AK Rifle",
    [Weapon.Pistol]: "Pistol",
    [Weapon.HuntingRifle]: "Hunting",
    [Weapon.RPG]: "RPG",
    [Weapon.Shotgun]: "Shotgun",
    [Weapon.SniperRifle]: "Sniper",
    [Weapon.SMG]: "SMG",
    [Weapon.Homing]: "Homing",
    [Weapon.Grenade]: "Grenade",
    [Weapon.HeliMinigun]: "Heli Minigun",
    [Weapon.TankMinigun]: "Tank Minigun",
    [Weapon.Knife]: "Knife",
    [Weapon.Revolver]: "Revolver",
    [Weapon.Minigun]: "Minigun",
    [Weapon.GrenadeLauncher]: "G. Launcher",
    [Weapon.UNKNOWN_WEAPON_82]: "Unknown Weapon 82",
    [Weapon.UNKNOWN_WEAPON_83]: "Unknown Weapon 83",
    [Weapon.UNKNOWN_WEAPON_84]: "Unknown Weapon 84",
    [Weapon.UNKNOWN_WEAPON_85]: "Unknown Weapon 85",
    [Weapon.UNKNOWN_WEAPON_86]: "Unknown Weapon 86",
    [Weapon.UNKNOWN_WEAPON_87]: "Unknown Weapon 87",
    [Weapon.Fists]: "Fists",
    [Weapon.VSS]: "VSS",
    [Weapon.FiftyCalSniper]: ".50 Cal Sniper",
    [Weapon.MGTurret]: "MG Turret",
    [Weapon.Crossbow]: "Crossbow",
    [Weapon.SCAR]: "SCAR",
    [Weapon.TacticalShotgun]: "Tactical Shotgun",
    [Weapon.VEK]: "VEK",
    [Weapon.UNKNOWN_WEAPON_96]: "Unknown Weapon 96",
    [Weapon.UNKNOWN_WEAPON_97]: "Unknown Weapon 97",
    [Weapon.LMG]: "LMG",
    [Weapon.UNKNOWN_WEAPON_103]: "Unknown Weapon 103",
    [Weapon.UNKNOWN_WEAPON_104]: "Unknown Weapon 104",
    [Weapon.UNKNOWN_WEAPON_105]: "Unknown Weapon 105",
    [Weapon.UNKNOWN_WEAPON_101]: "Unknown Weapon 101",
    [Weapon.UNKNOWN_WEAPON_110]: "Unknown Weapon 110",
    [Weapon.LaserTripMine]: "Laser Trip Mine",
    [Weapon.UNKNOWN_WEAPON_112]: "Unknown Weapon 112",
    [Weapon.UNKNOWN_WEAPON_126]: "Unknown Weapon 126",
}
