#!/usr/bin/env -S mise -E dev exec -- bash
#MISE description="Run all checks and tests"
#MISE alias="vv"
#MISE depends=["build", "check:spelling", "check:format", "check:lint", "check:types", "test:unit", "test:browser"]

set -euo pipefail
