name: Sync Labels

on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
      - .github/workflows/sync-labels.yml # this file
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEVELOPOMP_PAT }}
